#!/usr/bin/python3
import sys
import math


def is_prime(num):
    if num <= 1:
        return False
    if num <= 3:
        return True
    if num % 2 == 0 or num % 3 == 0:
        return False
    i = 5
    while i * i <= num:
        if num % i == 0 or num % (i + 2) == 0:
            return False
        i += 6
    return True


def smallest_prime_factor(n):
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0 and is_prime(i):
            return i
    return n


def factorize(n):
    factors = []
    while n != 1:
        factor = smallest_prime_factor(n)
        factors.append(factor)
        n //= factor
    return factors


if len(sys.argv) != 2:
    print("Usage: python rsa.py <file>")
    sys.exit(1)

filename = sys.argv[1]

try:
    with open(filename, "r") as file:
        for line in file:
            n = int(line.strip())
            prime_factors = factorize(n)
            prime_factors_str = "*".join(map(str, prime_factors))
            print(f"{n}={prime_factors_str}")

except FileNotFoundError:
    print(f"File '{filename}' not found.")
    sys.exit(1)
except ValueError:
    print("Invalid number in the file.")
    sys.exit(1)
